bookle/bookle/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path('logout/', include('django.contrib.auth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bookle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

bookle/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

from django.conf import settings

from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    
]

bookle/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

bookle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

bookle/core/models.py
from django.db import models

# Create your models here.

bookle/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Your password'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'Your Email'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Your password'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm your password'
                                                                ,'class':'w-full py-3 px-6 rounded-xl'}))

bookle/core/views.py
from django.shortcuts import render, redirect
from item.models import Item, Category
from .forms import SignupForm

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False,)[:6]
    categories = Category.objects.all()
    context = {
        'items': items,
        'categories': categories,
    }
    return render(request, 'core/index.html', context)


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()
    context = {
        'form': form
    }
    return render(request, 'core/signup.html', context)

bookle/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            label{
                color: aliceblue;
            }
        </style>
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Puddle</title>
    </head>
    <!-- Tailwind Navbar begins -->
    <body class="bg-slate-900">
        <nav class="bg-emerald-950 text-emerald-50 border-b border-gray-200 dark:bg-gray-900">
            <div class="container max-w-screen-lg mx-auto">
                <div class=" flex flex-wrap items-center justify-between mx-auto py-4 px-2">
                    <a href="/" class="flex items-center">
                    {% load static %}
                        <img src="{% static 'img/logo.png' %}" alt="">
                        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Bookle</span>
                    </a>
                    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-emerald-50 rounded-lg md:hidden hover:bg-emerald-800 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
                        <span class="sr-only">Open main menu</span>
                        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                    </button>
                    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
                        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border-t bg-emerald-950 md:flex-row md:space-x-4 md:mt-0 md:border-0 md:bg-emerald-950 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                        
                        <li>
                            <a href="{% url 'item:items' %}" class="text-md font-semibold hover:text-gray-500">Browse</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'item:new' %}" class="text-md font-semibold hover:text-gray-500">New Item</a>
                        </li>
                        <li>
                            <a href="{% url 'conversation:inbox' %}" class="md:px-5 md:py-2 text-md font-semibold  md:bg-emerald-700 text-white rounded-md hover:md:bg-emerald-800">Inbox</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:index' %}" class="md:px-5 md:py-2 text-md font-semibold  md:bg-gray-500 text-white rounded-md hover:md:bg-gray-700">Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}" class="md:px-5 md:py-2 text-md font-semibold  md:bg-red-500 text-white rounded-md md:hover:bg-red-700">Log Out ({{user.username}}) </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'core:signup' %}" class="md:px-5 md:py-2 text-md font-semibold  md:bg-cyan-700 text-white rounded-md hover:md:bg-cyan-800">Sign Up</a>
                        </li>
                        <li>
                            <a href="{% url 'core:login' %}" class="md:px-5 md:py-2 text-md font-semibold  md:bg-emerald-700 text-white rounded-md hover:md:bg-emerald-800">Log In</a>
                        </li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </div>          
        </nav>
    <!-- Tailwind Navbar Ends -->
        <div class="px-1 lg:px-6 py-6 container max-w-screen-lg mx-auto">
            {% block content %}
            
            {% endblock %}
        </div>

        <footer class="p-3 sm:py-6 sm:px-6 bg-emerald-950">
            <div class="container max-w-screen-lg mx-auto flex justify-between flex-col sm:flex-row" >
                <div class="sm:w-2/3 pr-10">
                    <h3 class="mb-5 font-semibold text-gray-300">About</h3>
    
                    <p class="text-lg text-gray-400">A Demo Project By Vahid using Django & Tailwind CSS.</p>
                </div>
    
                <div class="sm:w-1/3">
                    <h3 class="mb-5 font-semibold text-gray-300">Menu</h3>
    
                    <ul class="space-y-2">
                        <li><a href="{% url 'core:contact' %}" class="text-lg text-emerald-500 hover:text-emerald-700">Contact</a></li>
                        <li><a href="#" class="text-lg text-emerald-500 hover:text-emerald-700">Privacy policy</a></li>
                        <li><a href="#" class="text-lg text-emerald-500 hover:text-emerald-700">Term of use</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
              const btn = document.querySelector('[data-collapse-toggle="navbar-default"]');
              const menu = document.getElementById('navbar-default');
              
              btn.addEventListener('click', function () {
                menu.classList.toggle('hidden');
                menu.classList.toggle('block');
              });
            });
          </script>
    </body>
</html>

bookle/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}Contact{% endblock %}
{% block content %}
<h1 class="m-6 text-gray-100 font-bold text-2xl ">Visit Pythonology.eu or my Youtube channel @pythonology</h1>
{% endblock content %}

bookle/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class=" bg-gradient-to-r from-emerald-900 to-slate-900 py-9 text-white text-center rounded-md">
    <h1 class="font-bold text-5xl text-gray-100 ">Welcome to Bookle</h1>
    <h3 class="mt-4 text-2xl text-gray-100 ">Sell Your Second Hand Books Here</h3>
</div>

<div class="mt-6 px-2 lg:px-6 py-12 bg-emerald-900  rounded-md">
    <h2 class="mb-12 text-4xl font-black text-gray-100 text-center">New Items</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3  gap-3">
        {% for item in items %}
            <div class="bg-gray-100 rounded-md">
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" alt="" class=" rounded-t-md object-cover h-[150px] w-full" >
                    </div>
                    <div class="p-6 rounded-b-md">
                        <h2 class="text-2xl"> {{ item.name }} </h2>
                        <p class="text-gray-500">Price: {{ item.price }} </p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
</div>
<!-- Categories Section -->
<div class="my-6 px-4 py-12 bg-emerald-900 rounded-md max-w-screen-lg mx-auto">
    <h2 class="mb-12 text-2xl font-bold text-center text-gray-100">Categories</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <div class="p-4  bg-gray-100 rounded-b-md">
                <h2 class="text-2xl"> {{ category.name }} </h2>
                <hr class="my-3">
                <p class="text-gray-500">{{ category.items.count }} item{{category.items.count|pluralize}}</p>
            </div>
        </div>

        {% endfor %}
    </div>
{% endblock content %}

bookle/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Log in{% endblock %}
{% block content %}

<div class=" md:w-1/2 my-6 p-6  mx-auto bg-gray-100 rounded-xl ">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form action="." method="POST">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{form.username}}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-600 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}

bookle/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="md:w-1/2 my-6 p-6  mx-auto bg-gray-100 rounded-xl ">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form action="." method="POST">
        {% csrf_token %}
        
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-600 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}